random_forest:
  n_estimators: [50, 100, 200, 500]
  max_depth: [5, 8, 15, None, 10]
  min_samples_split: [2, 8, 15, 20]
  max_features: [5, 7, "auto", 8]

linear_regression: {}

svr:
  C: [0.1, 1, 10]
  kernel: ["linear", "rbf"]

lasso:
  alpha: [0.01, 0.1, 1.0]

ridge:
  alpha: [0.01, 0.1, 1.0]

adaboost:
  n_estimators: [50, 100, 150]
  learning_rate: [0.01, 0.1, 1.0]

gradient_boosting:
  learning_rate: [0.3, 0.03]
  n_estimators: [100, 200, 500]
  max_depth: [3, 6, 8, 10]
  subsample: [0.5, 0.7, 1]

knn:
  n_neighbors: [2, 3, 5, 7, 10, 20, 40]

decision_tree:
  max_depth: [5, 7, 10, 20]
