RandomForestRegressor:
  model__n_estimators: [50] #[50, 100, 200, 500]
  model__max_depth: [5] # [5, 8, 15, null, 10]
  model__min_samples_split: [2] # [2, 8, 15, 20]
  model__max_features: [5] # [5, 7, "sqrt", 8]
LinearRegression: {}
SVR:
  model__C: [0.1, 1, 10]
  model__kernel: ["linear", "rbf"]
Lasso:
  model__alpha: [0.01, 0.1, 1.0]
Ridge:
  model__alpha: [0.01, 0.1, 1.0]
AdaBoostRegressor:
  model__n_estimators: [50, 100, 150]
  model__learning_rate: [0.01, 0.1, 1.0]
GradientBoostingRegressor:
  model__learning_rate: [0.03] # [0.3, 0.03]
  model__n_estimators: [500] # [100, 200, 500]
  model__max_depth: [6] # [3, 6, 8, 10]
  model__subsample: [0.7] # [0.5, 0.7, 1]
KNeighborsRegressor:
  model__n_neighbors: [2, 3, 5, 7, 10, 20, 40]
DecisionTreeRegressor:
  model__max_depth: [5, 7, 10, 20]